server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
open:
  api:
    title: API-service document
    version: v1.0.0
    description: description for document
    serverUrl: http://localhost:${server.port}
    serverName: Server Dev