server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/my_tutorial_db}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:123abc}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:29092
open:
  api:
    title: API-service document
    version: v1.0.0
    description: description for document
    serverUrl: http://localhost:${server.port}
    serverName: Server Dev

jwt:
  accessKey: ${accessKey:b56wVKNjCBV14RqvpGAecIkb9+VtS+FLhHicaxRXlwk=}
  refreshKey: ${refreshKey:u04FsVPjRmoGsRq7QKyvGOuF018HI8EFTyH4C0ygYlM=}
  resetKey: ${resetKey:9d501d8c1fbdaed53457b6951e1c774db632fe896a55a524d94690b9c5223fb3}
  expiryHour: 1   # 1 hour
  expiryDay: 10   # 10 days