# Định nghĩa cho 3 môi trường chạy trên swagger
# mvn clean package -P dev || test || prod || ....
#  java -jar target/demo-0.0.1-SNAPSHOT.jar

spring:
  profiles:
    active: dev
    ## Nếu start bị lỗi @ thì nên set cứng chỗ này dev test hay prod cho nó chạy normal bình thường lại